version: '3.3'
name: books
services:
  api:
    build: .
    environment:
      BOOKS_API_PORT: ${BOOKS_API_PORT}
      BOOKS_DB_PORT: ${BOOKS_DB_PORT}
      AUTH_ENABLED: ${AUTH_ENABLED}
      BOOKS_REPOSITORY: ${BOOKS_REPOSITORY}
      BOOKS_DB_HOST: ${BOOKS_DB_HOST}
      BOOKS_DB_PASSWORD: ${BOOKS_DB_PASSWORD}
    networks:
      - bookstore
    ports:
      - "${BOOKS_API_PORT}:${BOOKS_API_PORT}"
  db:
    build: ./book-database
    networks:
      - bookstore
    environment:
      MYSQL_ROOT_PASSWORD: ${BOOKS_DB_PASSWORD}
      BOOKS_DB_PORT: ${BOOKS_DB_PORT}
    ports:
      - "${BOOKS_DB_PORT}:${BOOKS_DB_PORT}"

networks:
  bookstore:
